### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by acorn371** [kevmoo/git#31]
Hi,
I got the following error getting tags from my local git repository using **git 2.0.0**:

```
Unhandled exception:
Null check operator used on a null value
#0      Tag.parseCatFile (package:git/src/tag.dart:35:40)
#1      GitDir.tags (package:git/src/git_dir.dart:71:17)
```

My code worked fine when the repository had 2 tags but now, with 3 tags my code fails getting the third tag info, running the following code:

```
    final tags = <String,Tag>{};

    await for( var tag in gitDir.tags()) {
      tags[tag.objectSha] = tag;
    }
```

The exception is located in tag.dart from git package:

```
  static Tag parseCatFile(String content) {
     ...
    final objectSha = headers['object']!.single;  <== "Null check operator used on a null value"
    final type = headers['type']!.single;
    final tag = headers['tag']!.single;
    final tagger = headers['tagger']!.single;

    return Tag._internal(objectSha, type, tag, tagger);
  }
```

Regards,
Marco

**Comment by wgledbe** [comment]
Same error with (dart) git 2.2.0 and (git) git 2.35.1.

**Comment by wgledbe** [comment]
Like acorn371 mentions, the error comes out of `parseCatFile`, and throws when trying to index `headers['object']`. If I step into this function with the debugger, I see that the content of the cat file does not have `object` at all. Not only that, but it doesn't have _any_ of the headers that `parseCatFile` is looking for.

Turns out, this happens for "lightweight" tags whose `cat-file` output looks like a commit:
```text
tree 0f27f92b7df225c551281d28772c42462d430543
parent f424b58365278c8f6066d55cd5b7859658eb5ef8
author Me <wgledbe@sandia.gov> 1677190036 -0700
committer Me <wgledbe@sandia.gov> 1677190036 -0700

my intelligent commit message
```

Clearly, the solution is to add the capability to differentiate between annotated and lightweight tags. I think a "good enough" solution might be to do something like:
```dart
static Tag parseCatFile(String content, String tagSha, String tagName) {
  final headers = <String, List<String>>{};

  final slr = StringLineReader(content);

  var lastLine = slr.readNextLine()!;

  while (lastLine.isNotEmpty) {
    final match = headerRegExp.allMatches(lastLine).single;
    assert(match.groupCount == 2);
    final header = match.group(1)!;
    final value = match.group(2)!;

    headers.putIfAbsent(header, () => <String>[]).add(value);

    lastLine = slr.readNextLine()!;
  }

  String objectSha;
  String type;
  String tag;
  String tagger;

  if (headers['object'] != null) {
    // Annotated Tag
    objectSha = headers['object']!.single;
    type = headers['type']!.single;
    tag = headers['tag']!.single;
    tagger = headers['tagger']!.single;
  } else {
    // Lightweight Tag
    objectSha = tagSha;
    type = 'lightweight';
    tag = tagName;
    tagger = headers['author']!.single;
  }

  return Tag._internal(objectSha, type, tag, tagger);
}
```

This is not the most elegant solution, and you also have to change the `parseCatFile` call in `git_dir.dart`, but it works for my application.

**Comment by wgledbe** [comment]
Submitted PR #47 to close this issue.
